server:
  port: 80
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/redisdemo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 6
#  mvc:
#    pathmatch:
#      use-registered-suffix-pattern: true
#      use-suffix-pattern: true
  redis:
    # redis
#    host: 192.168.1.173
#    port: 7006
    # 集群
#    cluster:
#      nodes: 192.168.1.173:8000,192.168.1.173:8002,192.168.1.173:8003,192.168.1.173:8004,192.168.1.173:8005
    sentinel:
      nodes:
      master: mymaster
    database: 0
    lettuce:
      pool:
        max-wait: 15000
        max-idle: 10
        max-active: 10
        min-idle: 10
    timeout: 5000
